name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - pyarrow=2.0
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - jupyterlab=4.1.8
  - notebook=7.1.3
  - ipywidgets=8.1.2
  - jupyterlab_widgets
  - numba=0.59.1
  - pip=23.3.1
  - pip:
      - wandb==0.16.0
      - ydata_profiling
