name: nyc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - jupyterlab=4.1.8
  - notebook=7.1.3
  - ipywidgets=8.1.2
  - jupyterlab_widgets
  - numba=0.59.1
  - pip=23.3.1
  - pip:
      - mlflow[extras]
      - wandb
      - ydata_profiling==4.7.0
