name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - pandas=2.2.2
  - mlflow=2.11.3
  - jupyterlab=4.1.6
  - cookiecutter=2.6.0
  - hydra-core=1.3.2
  - pip=24.0
  - pip:
      - wandb==0.16.6
